attributes:
  LastSwiftUpdateCheck: '1420'
  LastUpgradeCheck: '0930'
  ORGANIZATIONNAME: Bucketeer
configs:
  Debug: debug
  Release: release
  Test: debug
name: Bucketeer
options:
  defaultConfig: Debug
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
configFiles:
  Debug: Resources/environment.xcconfig
  Release: Resources/environment.xcconfig
  Test: Resources/environment.xcconfig
schemes:
  Bucketeer:
    analyze:
      config: Debug
    archive:
      config: Release
    build:
      targets:
        Bucketeer:
        - running
        - testing
        - profiling
        - analyzing
        - archiving
    profile:
      config: Release
    run:
      config: Debug
    test:
      config: Debug
      environmentVariables:
      - value: $(E2E_API_ENDPOINT)
        variable: E2E_API_ENDPOINT
      - value: $(E2E_API_KEY)
        variable: E2E_API_KEY
      targets:
      - BucketeerTests
  BucketeerTVOS:
    analyze:
      config: Debug
    archive:
      config: Release
    build:
      targets:
        BucketeerTVOS:
        - running
        - testing
        - profiling
        - analyzing
        - archiving
    profile:
      config: Release
    run:
      config: Debug
    test:
      config: Debug
  Example:
    analyze:
      config: Debug
    archive:
      config: Release
    build:
      targets:
        Example:
        - running
        - testing
        - profiling
        - analyzing
        - archiving
    profile:
      config: Release
    run:
      config: Debug
      environmentVariables:
      - value: stub
        variable: API_KEY
      - value: stub
        variable: API_ENDPOINT
    test:
      config: Debug
  ExampleSwiftUI:
    analyze:
      config: Debug
    archive:
      config: Release
    build:
      targets:
        ExampleSwiftUI:
        - running
        - testing
        - profiling
        - analyzing
        - archiving
    profile:
      config: Release
    run:
      config: Debug
    test:
      config: Debug
  ExampleTVOS:
    analyze:
      config: Debug
    archive:
      config: Release
    build:
      targets:
        ExampleTVOS:
        - running
        - testing
        - profiling
        - analyzing
        - archiving
    profile:
      config: Release
    run:
      config: Debug
    test:
      config: Debug
settings:
  configs:
    Debug:
      CODE_SIGN_IDENTITY: iPhone Developer
      CURRENT_PROJECT_VERSION: '1'
      IPHONEOS_DEPLOYMENT_TARGET: '10.0'
      SDKROOT: iphoneos
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      SWIFT_VERSION: '5.0'
      VERSIONING_SYSTEM: apple-generic
      VERSION_INFO_PREFIX: ''
    Release:
      CODE_SIGN_IDENTITY: iPhone Developer
      CURRENT_PROJECT_VERSION: '1'
      IPHONEOS_DEPLOYMENT_TARGET: '10.0'
      SDKROOT: iphoneos
      SWIFT_OPTIMIZATION_LEVEL: -Owholemodule
      SWIFT_VERSION: '5.0'
      VERSIONING_SYSTEM: apple-generic
      VERSION_INFO_PREFIX: ''
    Test:
      CODE_SIGN_IDENTITY: iPhone Developer
      CURRENT_PROJECT_VERSION: '1'
      IPHONEOS_DEPLOYMENT_TARGET: '10.0'
      OTHER_SWIFT_FLAGS: -DTEST
      SDKROOT: iphoneos
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      SWIFT_VERSION: '5.0'
      VERSIONING_SYSTEM: apple-generic
      VERSION_INFO_PREFIX: ''
targets:
  Bucketeer:
    platform: iOS
    productName: Bucketeer
    settings:
      configs:
        Debug:
          BUILD_LIBRARY_FOR_DISTRIBUTION: 'YES'
          CLANG_CXX_LANGUAGE_STANDARD: gnu++17
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: Bucketeer/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: '11.0'
          IPHONEOS_DEPLOYMENT_TARGET[sdk=macosx*]: '13.1'
          MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
          MTL_FAST_MATH: 'YES'
          PRODUCT_BUNDLE_IDENTIFIER: io.bucketeer.sdk.ios
          SUPPORTED_PLATFORMS: appletvos appletvsimulator iphoneos iphonesimulator
          SUPPORTS_MACCATALYST: 'YES'
          SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: 'YES'
          SWIFT_EMIT_LOC_STRINGS: 'YES'
          SWIFT_VERSION: '5.0'
          TARGETED_DEVICE_FAMILY: 1,2,3
          TVOS_DEPLOYMENT_TARGET: '11.0'
        Release:
          BUILD_LIBRARY_FOR_DISTRIBUTION: 'YES'
          CLANG_CXX_LANGUAGE_STANDARD: gnu++17
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: Bucketeer/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: '11.0'
          IPHONEOS_DEPLOYMENT_TARGET[sdk=macosx*]: '13.1'
          MTL_FAST_MATH: 'YES'
          PRODUCT_BUNDLE_IDENTIFIER: io.bucketeer.sdk.ios
          SUPPORTED_PLATFORMS: appletvos appletvsimulator iphoneos iphonesimulator
          SUPPORTS_MACCATALYST: 'YES'
          SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: 'YES'
          SWIFT_EMIT_LOC_STRINGS: 'YES'
          SWIFT_VERSION: '5.0'
          TARGETED_DEVICE_FAMILY: 1,2,3
          TVOS_DEPLOYMENT_TARGET: '11.0'
        Test:
          BUILD_LIBRARY_FOR_DISTRIBUTION: 'YES'
          CLANG_CXX_LANGUAGE_STANDARD: gnu++17
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: Bucketeer/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: '11.0'
          IPHONEOS_DEPLOYMENT_TARGET[sdk=macosx*]: '13.1'
          MTL_FAST_MATH: 'YES'
          PRODUCT_BUNDLE_IDENTIFIER: io.bucketeer.sdk.ios
          SUPPORTED_PLATFORMS: appletvos appletvsimulator iphoneos iphonesimulator
          SUPPORTS_MACCATALYST: 'YES'
          SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: 'YES'
          SWIFT_EMIT_LOC_STRINGS: 'YES'
          SWIFT_VERSION: '5.0'
          TARGETED_DEVICE_FAMILY: 1,2,3
          TVOS_DEPLOYMENT_TARGET: '11.0'
    sources:
    - name: Bucketeer
      path: Bucketeer
    type: framework
  BucketeerTVOS:
    platform: iOS
    settings:
      configs:
        Debug:
          BUILD_LIBRARY_FOR_DISTRIBUTION: 'YES'
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: BucketeerTVOS/Info.plist
          MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
          MTL_FAST_MATH: 'YES'
          PRODUCT_BUNDLE_IDENTIFIER: io.bucketeer.sdk.tvos
          SDKROOT: appletvos
          SWIFT_VERSION: '5.0'
          TARGETED_DEVICE_FAMILY: '3'
          TVOS_DEPLOYMENT_TARGET: '11.0'
        Release:
          BUILD_LIBRARY_FOR_DISTRIBUTION: 'YES'
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: BucketeerTVOS/Info.plist
          MTL_FAST_MATH: 'YES'
          PRODUCT_BUNDLE_IDENTIFIER: io.bucketeer.sdk.tvos
          SDKROOT: appletvos
          SWIFT_VERSION: '5.0'
          TARGETED_DEVICE_FAMILY: '3'
          TVOS_DEPLOYMENT_TARGET: '11.0'
        Test:
          BUILD_LIBRARY_FOR_DISTRIBUTION: 'YES'
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: BucketeerTVOS/Info.plist
          MTL_FAST_MATH: 'YES'
          PRODUCT_BUNDLE_IDENTIFIER: io.bucketeer.sdk.tvos
          SDKROOT: appletvos
          SWIFT_VERSION: '5.0'
          TARGETED_DEVICE_FAMILY: '3'
          TVOS_DEPLOYMENT_TARGET: '11.0'
    sources:
    - name: BucketeerTVOS
      path: BucketeerTVOS
    type: framework
  BucketeerTests:
    dependencies:
    - target: Bucketeer
    platform: iOS
    productName: BucketeerTests
    settings:
      configs:
        Debug:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          CLANG_CXX_LANGUAGE_STANDARD: gnu++17
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_TEAM: 34LT9RJ65X
          GENERATE_INFOPLIST_FILE: 'YES'
          INFOPLIST_FILE: BucketeerTests/Info.plist
          INFOPLIST_KEY_LSApplicationCategoryType: ''
          IPHONEOS_DEPLOYMENT_TARGET: '15.5'
          MARKETING_VERSION: '1.0'
          MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
          MTL_FAST_MATH: 'YES'
          PRODUCT_BUNDLE_IDENTIFIER: io.bucketeer.sdk.ios.tests
          SWIFT_EMIT_LOC_STRINGS: 'NO'
          SWIFT_VERSION: '5.0'
        Release:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          CLANG_CXX_LANGUAGE_STANDARD: gnu++17
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_TEAM: 34LT9RJ65X
          GENERATE_INFOPLIST_FILE: 'YES'
          INFOPLIST_FILE: BucketeerTests/Info.plist
          INFOPLIST_KEY_LSApplicationCategoryType: ''
          IPHONEOS_DEPLOYMENT_TARGET: '15.5'
          MARKETING_VERSION: '1.0'
          MTL_FAST_MATH: 'YES'
          PRODUCT_BUNDLE_IDENTIFIER: io.bucketeer.sdk.ios.tests
          SWIFT_EMIT_LOC_STRINGS: 'NO'
          SWIFT_VERSION: '5.0'
        Test:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          CLANG_CXX_LANGUAGE_STANDARD: gnu++17
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_TEAM: 34LT9RJ65X
          GENERATE_INFOPLIST_FILE: 'YES'
          INFOPLIST_FILE: BucketeerTests/Info.plist
          INFOPLIST_KEY_LSApplicationCategoryType: ''
          IPHONEOS_DEPLOYMENT_TARGET: '15.5'
          MARKETING_VERSION: '1.0'
          MTL_FAST_MATH: 'YES'
          PRODUCT_BUNDLE_IDENTIFIER: io.bucketeer.sdk.ios.tests
          SWIFT_EMIT_LOC_STRINGS: 'NO'
          SWIFT_VERSION: '5.0'
    sources:
    - name: BucketeerTests
      path: BucketeerTests
    type: bundle.unit-test
  Example:
    dependencies:
    - target: Bucketeer
    platform: iOS
    settings:
      configs:
        Debug:
          CODE_SIGN_IDENTITY: Apple Development
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: 34LT9RJ65X
          GENERATE_INFOPLIST_FILE: 'NO'
          INFOPLIST_FILE: Example/Info.plist
          INFOPLIST_KEY_LSApplicationCategoryType: ''
          INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
          INFOPLIST_KEY_UIMainStoryboardFile: Main
          INFOPLIST_KEY_UIRequiredDeviceCapabilities: armv7
          INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
            UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationPortrait
            UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft
            UIInterfaceOrientationLandscapeRight
          IPHONEOS_DEPLOYMENT_TARGET: '11.0'
          PRODUCT_BUNDLE_IDENTIFIER: io.bucketeer.sdk.ios.example
          PROVISIONING_PROFILE_SPECIFIER: ''
          SWIFT_VERSION: '5.0'
        Release:
          CODE_SIGN_IDENTITY: Apple Development
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: 34LT9RJ65X
          GENERATE_INFOPLIST_FILE: 'NO'
          INFOPLIST_FILE: Example/Info.plist
          INFOPLIST_KEY_LSApplicationCategoryType: ''
          INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
          INFOPLIST_KEY_UIMainStoryboardFile: Main
          INFOPLIST_KEY_UIRequiredDeviceCapabilities: armv7
          INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
            UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationPortrait
            UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft
            UIInterfaceOrientationLandscapeRight
          IPHONEOS_DEPLOYMENT_TARGET: '11.0'
          PRODUCT_BUNDLE_IDENTIFIER: io.bucketeer.sdk.ios.example
          PROVISIONING_PROFILE_SPECIFIER: ''
          SWIFT_VERSION: '5.0'
        Test:
          CODE_SIGN_IDENTITY: Apple Development
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: 34LT9RJ65X
          GENERATE_INFOPLIST_FILE: 'NO'
          INFOPLIST_FILE: Example/Info.plist
          INFOPLIST_KEY_LSApplicationCategoryType: ''
          INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
          INFOPLIST_KEY_UIMainStoryboardFile: Main
          INFOPLIST_KEY_UIRequiredDeviceCapabilities: armv7
          INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
            UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationPortrait
            UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft
            UIInterfaceOrientationLandscapeRight
          IPHONEOS_DEPLOYMENT_TARGET: '11.0'
          PRODUCT_BUNDLE_IDENTIFIER: io.bucketeer.sdk.ios.example
          PROVISIONING_PROFILE_SPECIFIER: ''
          SWIFT_VERSION: '5.0'
    sources:
    - path: Example/AppDelegate.swift
    - path: Example/Assets.xcassets
    - name: Base.lproj
      path: Example/Base.lproj
    - path: Example/FirstViewController.swift
    - path: Example/Logger.swift
    - path: Example/SecondViewController.swift
    - path: Example/SplashViewController.swift
    - path: Example/ThirdViewController.swift
    type: application
  ExampleSwiftUI:
    dependencies:
    - target: Bucketeer
    platform: iOS
    productName: ExampleSwiftUI
    settings:
      configs:
        Debug:
          ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
          CLANG_CXX_LANGUAGE_STANDARD: gnu++20
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_ASSET_PATHS: '"ExampleSwiftUI/Preview Content"'
          DEVELOPMENT_TEAM: 4SVK7N5V6K
          GENERATE_INFOPLIST_FILE: 'YES'
          INFOPLIST_FILE: ExampleSwiftUI/Info.plist
          INFOPLIST_KEY_UIApplicationSceneManifest_Generation: 'YES'
          INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: 'YES'
          INFOPLIST_KEY_UILaunchScreen_Generation: 'YES'
          INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationLandscapeLeft
            UIInterfaceOrientationPortrait
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationLandscapeLeft
            UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown
          IPHONEOS_DEPLOYMENT_TARGET: '14.0'
          MARKETING_VERSION: '1.0'
          MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
          MTL_FAST_MATH: 'YES'
          PRODUCT_BUNDLE_IDENTIFIER: io.bucketeer.sdk.ios.ExampleSwiftUI
          SWIFT_EMIT_LOC_STRINGS: 'YES'
          SWIFT_VERSION: '5.0'
        Release:
          ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
          CLANG_CXX_LANGUAGE_STANDARD: gnu++20
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_ASSET_PATHS: '"ExampleSwiftUI/Preview Content"'
          DEVELOPMENT_TEAM: 4SVK7N5V6K
          GENERATE_INFOPLIST_FILE: 'YES'
          INFOPLIST_FILE: ExampleSwiftUI/Info.plist
          INFOPLIST_KEY_UIApplicationSceneManifest_Generation: 'YES'
          INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: 'YES'
          INFOPLIST_KEY_UILaunchScreen_Generation: 'YES'
          INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationLandscapeLeft
            UIInterfaceOrientationPortrait
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationLandscapeLeft
            UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown
          IPHONEOS_DEPLOYMENT_TARGET: '14.0'
          MARKETING_VERSION: '1.0'
          MTL_FAST_MATH: 'YES'
          PRODUCT_BUNDLE_IDENTIFIER: io.bucketeer.sdk.ios.ExampleSwiftUI
          SWIFT_EMIT_LOC_STRINGS: 'YES'
          SWIFT_VERSION: '5.0'
        Test:
          ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
          CLANG_CXX_LANGUAGE_STANDARD: gnu++20
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_ASSET_PATHS: '"ExampleSwiftUI/Preview Content"'
          DEVELOPMENT_TEAM: 4SVK7N5V6K
          GENERATE_INFOPLIST_FILE: 'YES'
          INFOPLIST_FILE: ExampleSwiftUI/Info.plist
          INFOPLIST_KEY_UIApplicationSceneManifest_Generation: 'YES'
          INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: 'YES'
          INFOPLIST_KEY_UILaunchScreen_Generation: 'YES'
          INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationLandscapeLeft
            UIInterfaceOrientationPortrait
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationLandscapeLeft
            UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown
          IPHONEOS_DEPLOYMENT_TARGET: '14.0'
          MARKETING_VERSION: '1.0'
          MTL_FAST_MATH: 'YES'
          PRODUCT_BUNDLE_IDENTIFIER: io.bucketeer.sdk.ios.ExampleSwiftUI
          SWIFT_EMIT_LOC_STRINGS: 'YES'
          SWIFT_VERSION: '5.0'
    sources:
    - name: ExampleSwiftUI
      path: ExampleSwiftUI
    type: application
  ExampleTVOS:
    dependencies:
    - target: Bucketeer
    platform: iOS
    settings:
      configs:
        Debug:
          ASSETCATALOG_COMPILER_APPICON_NAME: App Icon & Top Shelf Image
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_ASSET_PATHS: '"ExampleTVOS/Preview Content"'
          GENERATE_INFOPLIST_FILE: 'YES'
          INFOPLIST_FILE: ExampleTVOS/Info.plist
          INFOPLIST_KEY_LSApplicationCategoryType: ''
          MARKETING_VERSION: '1'
          MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
          MTL_FAST_MATH: 'YES'
          PRODUCT_BUNDLE_IDENTIFIER: io.bucketeer.sdk.tvos.example
          SDKROOT: appletvos
          SWIFT_VERSION: '5.0'
          TARGETED_DEVICE_FAMILY: '3'
          TVOS_DEPLOYMENT_TARGET: '11.0'
        Release:
          ASSETCATALOG_COMPILER_APPICON_NAME: App Icon & Top Shelf Image
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_ASSET_PATHS: '"ExampleTVOS/Preview Content"'
          GENERATE_INFOPLIST_FILE: 'YES'
          INFOPLIST_FILE: ExampleTVOS/Info.plist
          INFOPLIST_KEY_LSApplicationCategoryType: ''
          MARKETING_VERSION: '1'
          MTL_FAST_MATH: 'YES'
          PRODUCT_BUNDLE_IDENTIFIER: io.bucketeer.sdk.tvos.example
          SDKROOT: appletvos
          SWIFT_VERSION: '5.0'
          TARGETED_DEVICE_FAMILY: '3'
          TVOS_DEPLOYMENT_TARGET: '11.0'
        Test:
          ASSETCATALOG_COMPILER_APPICON_NAME: App Icon & Top Shelf Image
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_ASSET_PATHS: '"ExampleTVOS/Preview Content"'
          GENERATE_INFOPLIST_FILE: 'YES'
          INFOPLIST_FILE: ExampleTVOS/Info.plist
          INFOPLIST_KEY_LSApplicationCategoryType: ''
          MARKETING_VERSION: '1'
          MTL_FAST_MATH: 'YES'
          PRODUCT_BUNDLE_IDENTIFIER: io.bucketeer.sdk.tvos.example
          SDKROOT: appletvos
          SWIFT_VERSION: '5.0'
          TARGETED_DEVICE_FAMILY: '3'
          TVOS_DEPLOYMENT_TARGET: '11.0'
    sources:
    - name: ExampleTVOS
      path: ExampleTVOS
    type: application
